[project]
name = "triglav"
version = "0.1.0"
description = "A lisp based VM programming language"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["cryptography", "ruff", "numba"]

[tool.ruff.format]
indent-style = "tab"
quote-style = "preserve"
